// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWBxbvO86H8OSXYgi0lS1m_LOlD1OSW5U',
    appId: '1:422331683908:web:6d3806a06763fd1be7d811',
    messagingSenderId: '422331683908',
    projectId: 'kamino-3ba0c',
    authDomain: 'kamino-3ba0c.firebaseapp.com',
    storageBucket: 'kamino-3ba0c.appspot.com',
    measurementId: 'G-PH571CL8E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOdZItPPVs__loiLKK0bAwRS35TDUjjis',
    appId: '1:422331683908:android:4b29ac1393565b17e7d811',
    messagingSenderId: '422331683908',
    projectId: 'kamino-3ba0c',
    storageBucket: 'kamino-3ba0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAETV8K1532JWR7LwSC6qNhjVZItn00dDk',
    appId: '1:422331683908:ios:032e3e65617606fbe7d811',
    messagingSenderId: '422331683908',
    projectId: 'kamino-3ba0c',
    storageBucket: 'kamino-3ba0c.appspot.com',
    iosBundleId: 'com.example.kaminoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAETV8K1532JWR7LwSC6qNhjVZItn00dDk',
    appId: '1:422331683908:ios:032e3e65617606fbe7d811',
    messagingSenderId: '422331683908',
    projectId: 'kamino-3ba0c',
    storageBucket: 'kamino-3ba0c.appspot.com',
    iosBundleId: 'com.example.kaminoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWBxbvO86H8OSXYgi0lS1m_LOlD1OSW5U',
    appId: '1:422331683908:web:e66c02bbcd26a44ce7d811',
    messagingSenderId: '422331683908',
    projectId: 'kamino-3ba0c',
    authDomain: 'kamino-3ba0c.firebaseapp.com',
    storageBucket: 'kamino-3ba0c.appspot.com',
    measurementId: 'G-79CXDSJ51N',
  );
}
